//-----------------------------------------------------------------------
// <copyright file="ClientData.cs" company="Sully">
//     Copyright (c) Johnathon Sullinger. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
namespace MudDesigner.Adapters.Server
{
    using MudDesigner.Engine.Game;

    /// <summary>
    /// Represents data received or sent from the client.
    /// </summary>
    public sealed class ClientData
    {
        public ClientData(IPlayer player, IConnection connection, string data)
        {
            this.Player = player;
            this.Connection = connection;
            this.Data = data;
        }

        /// <summary>
        /// Gets the player that is the owner of the data.
        /// </summary>
        public IPlayer Player { get; }

        /// <summary>
        /// Gets the connection that the data is associated with.
        /// </summary>
        public IConnection Connection { get; }

        /// <summary>
        /// Gets the data generated by the player.
        /// </summary>
        public string Data { get; }
    }
}