namespace MudDesigner.Runtime
{
    /// <summary>
    /// A standard information message generated by the game
    /// </summary>
    public class InfoMessage : MessageBase<string>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InfoMessage"/> class.
        /// </summary>
        /// <param name="message">The message.</param>
        public InfoMessage(string message)
        {
            this.Content = message;
        }
    }
}
