//-----------------------------------------------------------------------
// <copyright file="InvalidWeatherStateException.cs" company="Sully">
//     Copyright (c) Johnathon Sullinger. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
namespace MudDesigner.Engine.Game
{
    using System;

    /// <summary>
    /// An exception generated by a time period being in an invalid state.
    /// </summary>
    public class InvalidWeatherStateException : Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InvalidWeatherStateException"/> class.
        /// </summary>
        /// <param name="state">The time period that is not valid.</param>
        /// <param name="message">The message.</param>
        public InvalidWeatherStateException(IWeatherState state, string message) : base(message)
        {
            this.Data.Add(state, message);
        }
    }
}
