//-----------------------------------------------------------------------
// <copyright file="InvalidTimePeriodException.cs" company="Sully">
//     Copyright (c) Johnathon Sullinger. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
namespace MudDesigner.Engine.Game
{
    using System;

    /// <summary>
    /// An exception generated by a time period being in an invalid state.
    /// </summary>
    public class InvalidTimePeriodException : Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InvalidTimePeriodException"/> class.
        /// </summary>
        /// <param name="period">The time period that is not valid.</param>
        /// <param name="message">The message.</param>
        public InvalidTimePeriodException(ITimePeriod period, string message) : base(message)
        {
            this.Data.Add(period, message);
        }
    }
}
